apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  {{- range $key, $val := .Values.secret }}
    {{- if $val }}
     {{ $key | indent 2  }}: {{ $val }}
    {{- end }}
  {{- end }}
