apiVersion: v1
data:
  ems-config.template: |-
    setprop factory TopicConnectionFactory URL=tcp://${env_ems_svc}:${env_ems_svc_port}
    setprop factory QueueConnectionFactory URL=tcp://${env_ems_svc}:${env_ems_svc_port}
    setprop factory GenericConnectionFactory URL=tcp://${env_ems_svc}:${env_ems_svc_port}
    set password ${env_ems_user} ${env_ems_new_password}
    commit
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-script-config