apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-properties-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
data:
  {{- range $key, $val := $.Values.extraEnv }}
     {{ $key | indent 2  }}: {{ $val| quote }}
  {{- end }}