apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
data:
  {{- range $key, $val := .Values.secret }}
    {{- if $val }}
     {{ $key | indent 2  }}: {{ $val }}
    {{- end }}
  {{- end }}
