apiVersion: v1
data:
  ems-config.template: |-
    set password {{ .Values.extraEnv.env_ems_user }} {{ .Values.extraEnv.env_ems_new_password }}
    setprop factory TopicConnectionFactory URL=tcp://{{ .Values.extraEnv.env_ems_svc }}:{{ .Values.extraEnv.env_ems_svc_port }}
    setprop factory QueueConnectionFactory URL=tcp://{{ .Values.extraEnv.env_ems_svc }}:{{ .Values.extraEnv.env_ems_svc_port }}
    setprop factory GenericConnectionFactory URL=tcp://{{ .Values.extraEnv.env_ems_svc }}:{{ .Values.extraEnv.env_ems_svc_port }}
    commit
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-script-config