kind: Service
apiVersion: v1
metadata:
  name: {{.Values.name }}-svc
  labels:
{{ include "ems.labels" $ | indent 4 }}
spec:
  type: {{ .Values.ems.service.type }}
  ports:
  - name: tibemsd-port
    port: {{ .Values.ems.service.port }}
    protocol: TCP
    targetPort: {{ .Values.ems.service.targetPort}}
  selector:
{{ include "ems.selectorLabels" $ | indent 4 }}
